model_name: "google/flan-t5-base"
api_url: "https://api-inference.huggingface.co/models/google/flan-t5-base"
api_key: "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"
temperature: 0.7
max_new_tokens: 150
prompt_prefix_1: |
  You are an expert in motor insurance fraud detection. In our historical data, fraudulent claims are extremely rare (below 1%). 
  No single feature strongly predicts fraud – instead, fraud emerges only from the combination of multiple subtle signals.
  Below are several historical claims, including a few fraudulent ones among many non-fraudulent cases. Use these examples as context.
prompt_prefix_2: |
  You are an expert in motor insurance fraud detection. In our historical data, fraudulent claims are extremely rare (below 1%). 
  No single feature strongly predicts fraud – instead, fraud emerges only from the combination of multiple subtle signals.
  Below are several historical claims, including a few fraudulent ones among many non-fraudulent cases. Use these examples as context.
num_retrievals: 5
