drop_columns:
  - ph_name # due to bias & GDPR reasons
  - ph_firstname
  - ph_gender
  - policy_insured_amount # due to low number of instances
  - sys_sector # due to 1 unique value
  - sys_label
  - sys_process
  - sys_product
  - sys_currency_code
story_columns:
  - object_make
  - object_year_construction
  - claim_causetype
  - claim_amount_claimed_total
  - claim_date_occurred
  - claim_date_reported
  - policy_profitability
  - policy_fleet_flag
